name: Auto Approve PRs
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@be2569198bf90722de218a28abce81786472b83a # v1.16.1
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
