name: CI
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-**"
      - "track/**"
    paths-ignore:
      - "terraform/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "terraform/**"

permissions:
  contents: read

jobs:
  openspec-check:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/openspec-check.yaml

  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@b5428d226e364de1c5ad601c1ec27c333f489d1d # v1.16.2
    with:
      base: "24.04"
      k8s-channel: "1.35-strict/stable"
      container-name: "identity-saml-provider"
      use-charmcraftcache: false
      node-size: large
      pytest-model-option: '--juju-model'
      juju-model-name: 'testing'
