name: CI
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-**"
      - "track/**"
    paths-ignore:
      - "terraform/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@d494c16b0ad34b623776893a37c2f70046d0587c # v1.12.1
    with:
      container-name: "identity-saml-provider"
      use-charmcraftcache: true
      node-size: large
      pytest-model-option: '--juju-model'
      juju-model-name: 'testing'
