name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        description: 'Origin Channel'
        type: string
        required: true
      destination-channel:
        description: 'Destination Channel'
        type: string
        required: true
      charmcraft-channel:
        description: 'Snap channel to use when installing charmcraft'
        required: false
        type: string
        default: 'latest/edge'

jobs:
  promote-charm:
      name: Promote Charm
      uses: canonical/identity-team/.github/workflows/charm-promotion.yaml@d494c16b0ad34b623776893a37c2f70046d0587c # v1.12.1
      with:
        origin-channel: ${{ github.event.inputs['origin-channel'] }}
        destination-channel: ${{ github.event.inputs['destination-channel'] }}
        charmcraft-channel: ${{ github.event.inputs['charmcraft-channel'] }}
      secrets:
        CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
