name: Publish Charm

on:
  push:
    tags:
      - "v**"
      - "track**"

  workflow_dispatch:
    inputs:
      destination_channel:
        description: CharmHub channel to publish to
        required: false
        default: 'latest/edge'
        type: string
      source_branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        required: false
        default: ''
        type: string

permissions:
  contents: read
  issues: write

jobs:
  publish:
    name: Publish Charm
    uses: canonical/identity-team/.github/workflows/charm-publish.yaml@d494c16b0ad34b623776893a37c2f70046d0587c # v1.12.1
    with:
      destination_channel: ${{ inputs.destination_channel}}
      source_branch: ${{ inputs.source_branch}}
      use-charmcraftcache: true
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS}}
