name: Publish Charm

on:
  push:
    tags:
      - "v**"
      - "track**"

  workflow_dispatch:
    inputs:
      destination_channel:
        description: CharmHub channel to publish to
        required: false
        default: 'latest/edge'
        type: string
      source_branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        required: false
        default: ''
        type: string

jobs:
  publish:
    name: Publish Charm
    uses: canonical/identity-team/.github/workflows/charm-publish.yaml@356ff61bd885e4147cc22c6eea64e4d806c889da # v1.11.3
    with:
      destination_channel: ${{ inputs.destination_channel}}
      source_branch: ${{ inputs.source_branch}}
      use-charmcraftcache: true
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS}}
