name: Publish Charm

on:
  push:
    tags:
      - "v**"
      - "track**"

  workflow_dispatch:
    inputs:
      destination_channel:
        description: CharmHub channel to publish to
        required: false
        default: 'latest/edge'
        type: string
      source_branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        required: false
        default: ''
        type: string

permissions:
  contents: write
  issues: write

jobs:
  publish:
    name: Publish Charm
    uses: canonical/identity-team/.github/workflows/charm-publish.yaml@fc85af7448538c473be450dc2c8ec5d158ea0d15 # v1.17.0
    with:
      destination_channel: ${{ inputs.destination_channel}}
      source_branch: ${{ inputs.source_branch}}
      use-charmcraftcache: false
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS}}
