name: Release-please

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release:
      name: release
      uses: canonical/identity-team/.github/workflows/charm-release.yaml@d494c16b0ad34b623776893a37c2f70046d0587c # v1.12.1
      secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
