name: Update Charm Libraries

on:
  workflow_dispatch:

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@d494c16b0ad34b623776893a37c2f70046d0587c # v1.12.1
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
